@baseUrl = http://localhost:3000/api/albums
 
# @name getAll
GET {{baseUrl}}

###

# @name add
POST {{baseUrl}}
Content-Type: application/json

{
    
}

###

# @name repair
PATCH {{baseUrl}}
Content-Type: application/json

{
    
}
###

# @name remove
DELETE  {{baseUrl}}
Content-Type: application/json
