@baseUrl = http://localhost:3000/api/totalPostsLikesUsers
 
# @name getAll
GET {{baseUrl}}

###

# @name add
POST {{baseUrl}}
Content-Type: application/json

{
    "email": "Andy99@hotmail.com",
    "password":"jizekovija""
}

###

# @name repair
PATCH {{baseUrl}}
Content-Type: application/json

{
    "name": "New PHP"
}
###

# @name remove
DELETE  {{baseUrl}}
Content-Type: application/json
